"""Evaluate the trained flagship models: budget sweep, baseline comparison,
and length-generalization breakdown, entirely on TEST_SEEN/TEST_UNSEEN —
splits the training loop in train.py never touches for anything (not
gradient updates, not early-stopping, not budget selection).

Writes a single machine-readable results/flagship-experiment.json. No
number in the README or UI is hand-typed; everything traces back to a
field in this file, generated by this script, from these checkpoints.

Usage: python research/flagship/evaluate.py [--checkpoint-dir DIR] [--out FILE]
"""

from __future__ import annotations

import argparse
import json
import statistics
from collections import defaultdict
from pathlib import Path

import torch

from model import OneShotBaseline, RecurrentReasoner
from task import GRID_SIZE, TEST_UNSEEN_LENGTH_RANGE, TRAIN_LENGTH_RANGE, generate_all_splits

SEEDS = (7, 13, 21)
THINKING_STEPS_TRAIN = 4
HIDDEN_SIZE = 64
BUDGET_SWEEP = (0, 1, 2, 4, 8, 16, 24)


def encode_moves(moves_batch: list[list[int]], max_len: int) -> tuple[torch.Tensor, torch.Tensor]:
    padded = torch.zeros(len(moves_batch), max_len, dtype=torch.float32)
    lengths = torch.zeros(len(moves_batch), dtype=torch.long)
    for i, moves in enumerate(moves_batch):
        lengths[i] = len(moves)
        for j, move in enumerate(moves):
            padded[i, j] = 1.0 if move == 1 else -1.0
    return padded, lengths


def mean_std(values: list[float]) -> dict:
    return {
        "mean": statistics.fmean(values),
        "std": statistics.pstdev(values) if len(values) > 1 else 0.0,
        "values": values,
    }


def accuracy(logits: torch.Tensor, labels: torch.Tensor) -> float:
    return float((logits.argmax(dim=1) == labels).float().mean().item())


def per_length_accuracy(logits: torch.Tensor, labels: torch.Tensor, lengths: torch.Tensor) -> dict:
    correct = (logits.argmax(dim=1) == labels)
    buckets: dict[int, list[bool]] = defaultdict(list)
    for i in range(lengths.shape[0]):
        buckets[int(lengths[i].item())].append(bool(correct[i].item()))
    return {str(length): (sum(bools) / len(bools)) for length, bools in sorted(buckets.items())}


def evaluate_recurrent(checkpoint_path: Path, split, max_len: int) -> dict:
    model = RecurrentReasoner(hidden_size=HIDDEN_SIZE, grid_size=GRID_SIZE)
    model.load_state_dict(torch.load(checkpoint_path, weights_only=True))
    model.eval()
    moves, lengths = encode_moves(split.moves, max_len)
    labels = torch.tensor(split.labels, dtype=torch.long)

    by_budget = {}
    by_budget_length = {}
    with torch.no_grad():
        for budget in BUDGET_SWEEP:
            logits, _ = model(moves, lengths, budget)
            by_budget[str(budget)] = accuracy(logits, labels)
            by_budget_length[str(budget)] = per_length_accuracy(logits, labels, lengths)
    return {"byBudget": by_budget, "byBudgetAndLength": by_budget_length}


def evaluate_baseline(checkpoint_path: Path, split) -> dict:
    model = OneShotBaseline(grid_size=GRID_SIZE)
    model.load_state_dict(torch.load(checkpoint_path, weights_only=True))
    model.eval()
    features = OneShotBaseline.featurize(split.moves)
    labels = torch.tensor(split.labels, dtype=torch.long)
    lengths = torch.tensor([len(m) for m in split.moves], dtype=torch.long)
    with torch.no_grad():
        logits = model(features)
    return {"accuracy": accuracy(logits, labels), "byLength": per_length_accuracy(logits, labels, lengths)}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint-dir", default=str(Path(__file__).resolve().parent / "checkpoints"))
    parser.add_argument("--out", default=str(Path(__file__).resolve().parent.parent.parent / "results" / "flagship-experiment.json"))
    args = parser.parse_args()
    checkpoint_dir = Path(args.checkpoint_dir)

    splits = generate_all_splits()
    test_seen, test_unseen = splits["test_seen"], splits["test_unseen"]
    max_len = max(TRAIN_LENGTH_RANGE[1], TEST_UNSEEN_LENGTH_RANGE[1])

    results = {
        "config": {
            "gridSize": GRID_SIZE,
            "hiddenSize": HIDDEN_SIZE,
            "thinkingStepsTrain": THINKING_STEPS_TRAIN,
            "budgetSweep": list(BUDGET_SWEEP),
            "seeds": list(SEEDS),
            "trainLengthRange": list(TRAIN_LENGTH_RANGE),
            "testUnseenLengthRange": list(TEST_UNSEEN_LENGTH_RANGE),
            "splitSizes": {name: len(split) for name, split in splits.items()},
        },
        "recurrent": {"testSeen": {"perSeed": []}, "testUnseen": {"perSeed": []}},
        "baseline": {"testSeen": {"perSeed": []}, "testUnseen": {"perSeed": []}},
    }

    for seed in SEEDS:
        recurrent_ckpt = checkpoint_dir / f"recurrent-seed{seed}.pt"
        seen_result = evaluate_recurrent(recurrent_ckpt, test_seen, max_len)
        unseen_result = evaluate_recurrent(recurrent_ckpt, test_unseen, max_len)
        results["recurrent"]["testSeen"]["perSeed"].append({"seed": seed, **seen_result})
        results["recurrent"]["testUnseen"]["perSeed"].append({"seed": seed, **unseen_result})

        baseline_ckpt = checkpoint_dir / f"baseline-seed{seed}.pt"
        results["baseline"]["testSeen"]["perSeed"].append({"seed": seed, **evaluate_baseline(baseline_ckpt, test_seen)})
        results["baseline"]["testUnseen"]["perSeed"].append({"seed": seed, **evaluate_baseline(baseline_ckpt, test_unseen)})

    # Aggregate mean/std across seeds, per budget, per split — this is what
    # the README/UI budget->accuracy chart actually reads.
    for split_name in ("testSeen", "testUnseen"):
        per_seed = results["recurrent"][split_name]["perSeed"]
        aggregated = {}
        for budget in BUDGET_SWEEP:
            values = [entry["byBudget"][str(budget)] for entry in per_seed]
            aggregated[str(budget)] = mean_std(values)
        results["recurrent"][split_name]["aggregatedByBudget"] = aggregated

        baseline_values = [entry["accuracy"] for entry in results["baseline"][split_name]["perSeed"]]
        results["baseline"][split_name]["aggregated"] = mean_std(baseline_values)

    # Aggregate mean/std across seeds, per exact sequence length, at the
    # THINKING_STEPS_TRAIN budget — deliberately the fixed training budget
    # decided before any test result existed, not a budget picked because
    # it scored best on test data (that would be tuning on the test set).
    # This is what the README/UI length->accuracy (extrapolation) chart
    # reads; the full budget sweep above is reported regardless, untouched.
    for split_name in ("testSeen", "testUnseen"):
        budget = THINKING_STEPS_TRAIN
        per_seed = results["recurrent"][split_name]["perSeed"]
        lengths = sorted({int(length) for entry in per_seed for length in entry["byBudgetAndLength"][str(budget)]}, key=int)
        by_length = {}
        for length in lengths:
            values = [entry["byBudgetAndLength"][str(budget)][str(length)] for entry in per_seed]
            by_length[str(length)] = mean_std(values)
        results["recurrent"][split_name]["lengthChartBudget"] = budget
        results["recurrent"][split_name]["aggregatedByLengthAtTrainingBudget"] = by_length

        baseline_per_seed = results["baseline"][split_name]["perSeed"]
        baseline_by_length = {}
        for length in lengths:
            values = [entry["byLength"].get(str(length), None) for entry in baseline_per_seed]
            values = [v for v in values if v is not None]
            if values:
                baseline_by_length[str(length)] = mean_std(values)
        results["baseline"][split_name]["aggregatedByLength"] = baseline_by_length

    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text(json.dumps(results, indent=2))
    print(f"Wrote {args.out}")

    for split_name in ("testSeen", "testUnseen"):
        print(f"\n{split_name}:")
        for budget in BUDGET_SWEEP:
            agg = results["recurrent"][split_name]["aggregatedByBudget"][str(budget)]
            print(f"  budget={budget:>2}  recurrent={agg['mean']*100:5.1f}% (+/-{agg['std']*100:4.1f})")
        base = results["baseline"][split_name]["aggregated"]
        print(f"  baseline (one-shot) = {base['mean']*100:5.1f}% (+/-{base['std']*100:4.1f})")


if __name__ == "__main__":
    main()
